In [5]:
import pandas as pd

In [12]:
table=pd.read_excel('ToyotaCorolla.xls',sheet_name='data')

In [13]:
table

,Id,Model,Price,Age_08_04,Mfg_Month,Mfg_Year,KM,Fuel_Type,HP,Met_Color,...,Powered_Windows,Power_Steering,Radio,Mistlamps,Sport_Model,Backseat_Divider,Metallic_Rim,Radio_cassette,Parking_Assistant,Tow_Bar
0,1,TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors,13500,23,10,2002,46986,Diesel,90,1,...,1,1,0,0,0,1,0,0,0,0
1,2,TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors,13750,23,10,2002,72937,Diesel,90,1,...,0,1,0,0,0,1,0,0,0,0
2,3,TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors,13950,24,9,2002,41711,Diesel,90,1,...,0,1,0,0,0,1,0,0,0,0
3,4,TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors,14950,26,7,2002,48000,Diesel,90,0,...,0,1,0,0,0,1,0,0,0,0
4,5,TOYOTA Corolla 2.0 D4D HATCHB SOL 2/3-Doors,13750,30,3,2002,38500,Diesel,90,0,...,1,1,0,1,0,1,0,0,0,0
5,6,TOYOTA Corolla 2.0 D4D HATCHB SOL 2/3-Doors,12950,32,1,2002,61000,Diesel,90,0,...,1,1,0,1,0,1,0,0,0,0
6,7,TOYOTA Corolla 2.0 D4D 90 3DR TERRA 2/3-Doors,16900,27,6,2002,94612,Diesel,90,1,...,1,1,0,0,1,1,0,0,0,0
7,8,TOYOTA Corolla 2.0 D4D 90 3DR TERRA 2/3-Doors,18600,30,3,2002,75889,Diesel,90,1,...,1,1,0,0,0,1,0,0,0,0
8,9,TOYOTA Corolla 1800 T SPORT VVT I 2/3-Doors,21500,27,6,2002,19700,Petrol,192,0,...,1,1,1,0,0,0,1,1,0,0
9,10,TOYOTA Corolla 1.9 D HATCHB TERRA 2/3-Doors,12950,23,10,2002,71138,Diesel,69,0,...,0,1,0,0,0,1,0,0,0,0
10,11,TOYOTA Corolla 1.8 VVTL-i T-Sport 3-Drs 2/3-Doors,20950,25,8,2002,31461,Petrol,192,0,...,1,1,0,0,0,0,1,0,0,0
11,12,TOYOTA Corolla 1.8 16V VVTLI 3DR T SPORT BNS 2...,19950,22,11,2002,43610,Petrol,192,0,...,1,1,0,1,1,1,1,0,0,0
12,13,TOYOTA Corolla 1.8 16V VVTLI 3DR T SPORT 2/3-D...,19600,25,8,2002,32189,Petrol,192,0,...,1,1,0,1,1,1,1,0,0,0
13,14,TOYOTA Corolla 1.8 16V VVTLI 3DR T SPORT 2/3-D...,21500,31,2,2002,23000,Petrol,192,1,...,1,1,0,1,1,1,1,0,0,0
14,15,TOYOTA Corolla 1.8 16V VVTLI 3DR T SPORT 2/3-D...,22500,32,1,2002,34131,Petrol,192,1,...,1,1,0,1,1,1,1,0,0,0
15,16,TOYOTA Corolla 1.8 16V VVTLI 3DR T SPORT 2/3-D...,22000,28,5,2002,18739,Petrol,192,0,...,1,1,0,1,1,1,1,0,0,0
16,17,TOYOTA Corolla 1.8 16V VVTLI 3DR T SPORT 2/3-...,22750,30,3,2002,34000,Petrol,192,1,...,1,1,0,1,0,1,1,0,0,0
17,18,TOYOTA Corolla 1.6 VVTI Linea Terra Comfort 2...,17950,24,9,2002,21716,Petrol,110,1,...,1,1,1,0,0,0,0,1,0,1
18,19,TOYOTA Corolla 1.6 16v L.SOL 2/3-Doors,16750,24,9,2002,25563,Petrol,110,0,...,1,1,0,1,0,0,0,0,0,0
19,20,TOYOTA Corolla 1.6 16V VVT I 3DR TERRA 2/3-Doors,16950,30,3,2002,64359,Petrol,110,1,...,1,1,0,0,1,1,0,0,0,0
20,21,TOYOTA Corolla 1.6 16V VVT I 3DR TERRA 2/3-Doors,15950,30,3,2002,67660,Petrol,110,1,...,1,1,0,0,1,1,0,0,0,1
21,22,TOYOTA Corolla 1.6 16V VVT I 3DR SOL AUT4 2/3-...,16950,29,4,2002,43905,Petrol,110,0,...,1,1,0,1,1,1,0,0,0,0
22,23,TOYOTA Corolla 1.6 16V VVT I 3DR SOL 2/3-Doors,15950,28,5,2002,56349,Petrol,110,1,...,1,1,0,1,1,1,1,0,0,1
23,24,TOYOTA Corolla 1.6 16V VVT I 3DR SOL 2/3-Doors,16950,28,5,2002,32220,Petrol,110,1,...,1,1,0,1,1,1,0,0,0,0
24,25,TOYOTA Corolla 1.6 16V VVT I 3DR SOL 2/3-Doors,16250,29,4,2002,25813,Petrol,110,1,...,1,1,0,1,1,1,0,0,0,0
25,26,TOYOTA Corolla 1.6 16V VVT I 3DR SOL 2/3-Doors,15950,25,8,2002,28450,Petrol,110,1,...,1,1,0,1,1,1,1,0,0,1
26,27,TOYOTA Corolla 1.6 16V VVT I 3DR SOL 2/3-Doors,17495,27,6,2002,34545,Petrol,110,1,...,1,1,0,1,0,1,1,0,0,0
27,28,TOYOTA Corolla 1.6 16V VVT I 3DR SOL 2/3-Doors,15750,29,4,2002,41415,Petrol,110,1,...,1,1,0,1,1,1,1,0,0,0
28,29,TOYOTA Corolla 1.6 16V VVT I 3DR SOL 2/3-Doors,16950,28,5,2002,44142,Petrol,110,0,...,1,1,0,1,1,1,0,0,0,0
29,30,TOYOTA Corolla 1.6 16V VVT I 3DR SOL 2/3-Doors,17950,30,3,2002,11090,Petrol,110,1,...,1,1,0,1,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1406,1413,TOYOTA Corolla 1.6 16V HATCHB LINEA TERRA 2/3-...,8950,70,11,1998,44850,Petrol,110,1,...,0,1,0,0,1,1,0,0,0,0
1407,1414,TOYOTA Corolla 1.6 GL LB 4/5-Doors,8250,69,12,1998,44826,Petrol,110,0,...,1,1,0,0,0,1,0,0,0,1
1408,1415,TOYOTA Corolla 1.6 16V HATCHB GTSI 2/3-Doors,9250,80,1,1998,44444,Petrol,110,1,...,1,1,0,1,1,1,1,0,0,0
1409,1416,TOYOTA Corolla 1.6 16V LIFTB LINEA TERRA 4/5-D...,7900,75,6,1998,43720,Petrol,110,1,...,0,1,0,0,1,1,0,0,0,1
1410,1417,TOYOTA Corolla 1.3 16V SEDAN LINEA TERRA 4/5-D...,8500,78,3,1998,43622,Petrol,86,1,...,0,1,0,0,0,0,0,0,0,0
1411,1418,TOYOTA Corolla 1.6 16V LIFTB LINEA TERRA 4/5-D...,7950,76,5,1998,43532,Petrol,110,0,...,0,1,0,0,0,1,0,0,0,0
1412,1419,TOYOTA Corolla 1.6 16V HATCHB LINEA TERRA 2/3-...,9950,69,12,1998,42800,Petrol,110,1,...,0,1,0,0,1,1,0,0,0,0
1413,1420,TOYOTA Corolla 1.6 16V LIFTB LINEA TERRA AUT4 ...,8750,74,7,1998,42317,Petrol,107,1,...,0,1,1,1,0,1,0,1,0,1
1414,1421,TOYOTA Corolla 1.6 16V HATCHB LINEA TERRA 2/3-...,7500,80,1,1998,42186,Petrol,110,1,...,0,1,0,1,0,1,0,0,0,1
1415,1422,TOYOTA Corolla 1.6 16V HATCHB LINEA TERRA 2/3-...,6950,72,9,1998,42000,Petrol,110,1,...,0,1,0,0,1,1,0,0,0,0
1416,1423,TOYOTA Corolla 1.6 LB 4/5-Doors,8950,79,2,1998,40093,Petrol,110,0,...,0,1,1,0,0,0,0,1,0,0
1417,1424,TOYOTA Corolla 1.6 16V HATCHB LINEA TERRA AUT4...,8750,79,2,1998,39800,Petrol,107,0,...,0,1,0,0,1,1,0,0,0,0
1418,1425,TOYOTA Corolla 1.3 16V HATCHB LINEA TERRA 2/3-...,7750,73,8,1998,39168,Petrol,86,0,...,0,1,0,0,1,1,0,0,0,0
1419,1426,TOYOTA Corolla 1.6 16V HATCHB LINEA TERRA 2/3-...,8450,75,6,1998,38945,Petrol,110,1,...,1,1,0,0,0,1,1,0,0,0
1420,1427,TOYOTA Corolla 1.6 SDN LINEA TERRA AUT 4/5-Doors,8150,76,5,1998,36537,Petrol,110,0,...,0,0,0,0,0,0,0,0,0,0
1421,1428,TOYOTA Corolla 1.3 16V HATCHB LINEA TERRA AUT3...,8500,78,3,1998,36000,Petrol,86,0,...,0,1,0,0,0,1,0,0,0,0
1422,1429,TOYOTA Corolla 1.6 16V HATCHB LINEA TERRA 2/3-...,7600,78,3,1998,36000,Petrol,110,1,...,1,1,0,0,0,1,1,0,0,0
1423,1430,TOYOTA Corolla 1.3 HB LINEA TERRA AUT 2/3-Doors,7950,80,1,1998,35821,Petrol,86,0,...,0,1,0,0,0,0,0,0,0,0
1424,1431,TOYOTA Corolla 1.3 3D Linea Terra 2/3-Doors,7750,73,8,1998,34717,Petrol,86,0,...,0,1,0,0,0,0,0,0,0,0
1425,1432,TOYOTA Corolla 1.3 Linea Terra sedan 4/5-Doors,7950,80,1,1998,34000,Petrol,86,1,...,0,0,0,0,0,0,0,0,0,0
1426,1433,TOYOTA Corolla 1.6 Lin.Terra Aut. 2/3-Doors,9950,78,3,1998,30964,Petrol,110,0,...,0,1,0,0,0,0,0,0,0,1
1427,1434,TOYOTA Corolla 1.3 16V HATCHB LINEA TERRA AUT3...,8950,71,10,1998,29000,Petrol,86,1,...,0,1,0,0,0,1,0,0,0,0
1428,1435,TOYOTA Corolla 1.3 16V HATCHB LINEA TERRA 2/3-...,8450,72,9,1998,26000,Petrol,86,0,...,0,1,0,0,1,1,0,0,0,0
1429,1436,TOYOTA Corolla 1.3 Linea Terra 4/5-Doors,8950,78,3,1998,24000,Petrol,86,1,...,0,1,0,0,0,0,0,0,0,1
1430,1437,TOYOTA Corolla 1.3 16V HATCHB LINEA TERRA 2/3-...,8450,80,1,1998,23000,Petrol,86,0,...,0,1,0,0,1,1,1,0,0,0
1431,1438,TOYOTA Corolla 1.3 16V HATCHB G6 2/3-Doors,7500,69,12,1998,20544,Petrol,86,1,...,1,1,0,1,1,1,0,0,0,0
1432,1439,TOYOTA Corolla 1.3 16V HATCHB LINEA TERRA 2/3-...,10845,72,9,1998,19000,Petrol,86,0,...,0,1,0,0,1,1,0,0,0,0
1433,1440,TOYOTA Corolla 1.3 16V HATCHB LINEA TERRA 2/3-...,8500,71,10,1998,17016,Petrol,86,0,...,0,1,0,0,0,1,0,0,0,0
1434,1441,TOYOTA Corolla 1.3 16V HATCHB LINEA TERRA 2/3-...,7250,70,11,1998,16916,Petrol,86,1,...,0,0,0,0,0,1,0,0,0,0
1435,1442,TOYOTA Corolla 1.6 LB LINEA TERRA 4/5-Doors,6950,76,5,1998,1,Petrol,110,0,...,0,1,0,0,0,0,0,0,0,0

In [17]:
table.columns

Index([u'Id', u'Model', u'Price', u'Age_08_04', u'Mfg_Month', u'Mfg_Year',
       u'KM', u'Fuel_Type', u'HP', u'Met_Color', u'Color', u'Automatic', u'CC',
       u'Doors', u'Cylinders', u'Gears', u'Quarterly_Tax', u'Weight',
       u'Mfr_Guarantee', u'BOVAG_Guarantee', u'Guarantee_Period', u'ABS',
       u'Airbag_1', u'Airbag_2', u'Airco', u'Automatic_airco',
       u'Boardcomputer', u'CD_Player', u'Central_Lock', u'Powered_Windows',
       u'Power_Steering', u'Radio', u'Mistlamps', u'Sport_Model',
       u'Backseat_Divider', u'Metallic_Rim', u'Radio_cassette',
       u'Parking_Assistant', u'Tow_Bar'],
      dtype='object')

In [19]:
table[['Id']]

        Id
0        1
1        2
2        3
3        4
4        5
5        6
6        7
7        8
8        9
9       10
10      11
11      12
12      13
13      14
14      15
15      16
16      17
17      18
18      19
19      20
20      21
21      22
22      23
23      24
24      25
25      26
26      27
27      28
28      29
29      30
...    ...
1406  1413
1407  1414
1408  1415
1409  1416
1410  1417
1411  1418
1412  1419
1413  1420
1414  1421
1415  1422
1416  1423
1417  1424
1418  1425
1419  1426
1420  1427
1421  1428
1422  1429
1423  1430
1424  1431
1425  1432
1426  1433
1427  1434
1428  1435
1429  1436
1430  1437
1431  1438
1432  1439
1433  1440
1434  1441
1435  1442

[1436 rows x 1 columns]

In [31]:
temp_table = table [['Age_08_04', 'Mfg_Month', 'Mfg_Year',
       'KM', 'Fuel_Type', 'HP', 'Met_Color', 'Color', 'Automatic', 'CC',
       'Doors', 'Cylinders', 'Gears', 'Quarterly_Tax', 'Weight',
       'Mfr_Guarantee', 'BOVAG_Guarantee', 'Guarantee_Period', 'ABS',
       'Airbag_1', 'Airbag_2', 'Airco', 'Automatic_airco',
       'Boardcomputer', 'CD_Player', 'Central_Lock', 'Powered_Windows',
       'Power_Steering', 'Radio', 'Mistlamps', 'Sport_Model',
       'Backseat_Divider', 'Metallic_Rim', 'Radio_cassette',
       'Parking_Assistant', 'Tow_Bar' ]]
temp_table

,Age_08_04,Mfg_Month,Mfg_Year,KM,Fuel_Type,HP,Met_Color,Color,Automatic,CC,...,Powered_Windows,Power_Steering,Radio,Mistlamps,Sport_Model,Backseat_Divider,Metallic_Rim,Radio_cassette,Parking_Assistant,Tow_Bar
0,23,10,2002,46986,Diesel,90,1,Blue,0,2000,...,1,1,0,0,0,1,0,0,0,0
1,23,10,2002,72937,Diesel,90,1,Silver,0,2000,...,0,1,0,0,0,1,0,0,0,0
2,24,9,2002,41711,Diesel,90,1,Blue,0,2000,...,0,1,0,0,0,1,0,0,0,0
3,26,7,2002,48000,Diesel,90,0,Black,0,2000,...,0,1,0,0,0,1,0,0,0,0
4,30,3,2002,38500,Diesel,90,0,Black,0,2000,...,1,1,0,1,0,1,0,0,0,0
5,32,1,2002,61000,Diesel,90,0,White,0,2000,...,1,1,0,1,0,1,0,0,0,0
6,27,6,2002,94612,Diesel,90,1,Grey,0,2000,...,1,1,0,0,1,1,0,0,0,0
7,30,3,2002,75889,Diesel,90,1,Grey,0,2000,...,1,1,0,0,0,1,0,0,0,0
8,27,6,2002,19700,Petrol,192,0,Red,0,1800,...,1,1,1,0,0,0,1,1,0,0
9,23,10,2002,71138,Diesel,69,0,Blue,0,1900,...,0,1,0,0,0,1,0,0,0,0
10,25,8,2002,31461,Petrol,192,0,Silver,0,1800,...,1,1,0,0,0,0,1,0,0,0
11,22,11,2002,43610,Petrol,192,0,Red,0,1800,...,1,1,0,1,1,1,1,0,0,0
12,25,8,2002,32189,Petrol,192,0,Red,0,1800,...,1,1,0,1,1,1,1,0,0,0
13,31,2,2002,23000,Petrol,192,1,Black,0,1800,...,1,1,0,1,1,1,1,0,0,0
14,32,1,2002,34131,Petrol,192,1,Grey,0,1800,...,1,1,0,1,1,1,1,0,0,0
15,28,5,2002,18739,Petrol,192,0,Grey,0,1800,...,1,1,0,1,1,1,1,0,0,0
16,30,3,2002,34000,Petrol,192,1,Grey,0,1800,...,1,1,0,1,0,1,1,0,0,0
17,24,9,2002,21716,Petrol,110,1,Blue,0,1600,...,1,1,1,0,0,0,0,1,0,1
18,24,9,2002,25563,Petrol,110,0,Grey,0,1600,...,1,1,0,1,0,0,0,0,0,0
19,30,3,2002,64359,Petrol,110,1,Grey,0,1600,...,1,1,0,0,1,1,0,0,0,0
20,30,3,2002,67660,Petrol,110,1,Blue,0,1600,...,1,1,0,0,1,1,0,0,0,1
21,29,4,2002,43905,Petrol,110,0,Grey,1,1600,...,1,1,0,1,1,1,0,0,0,0
22,28,5,2002,56349,Petrol,110,1,Black,0,1600,...,1,1,0,1,1,1,1,0,0,1
23,28,5,2002,32220,Petrol,110,1,Black,0,1600,...,1,1,0,1,1,1,0,0,0,0
24,29,4,2002,25813,Petrol,110,1,Grey,0,1600,...,1,1,0,1,1,1,0,0,0,0
25,25,8,2002,28450,Petrol,110,1,Blue,0,1600,...,1,1,0,1,1,1,1,0,0,1
26,27,6,2002,34545,Petrol,110,1,Blue,0,1600,...,1,1,0,1,0,1,1,0,0,0
27,29,4,2002,41415,Petrol,110,1,Black,0,1600,...,1,1,0,1,1,1,1,0,0,0
28,28,5,2002,44142,Petrol,110,0,Grey,0,1600,...,1,1,0,1,1,1,0,0,0,0
29,30,3,2002,11090,Petrol,110,1,Blue,0,1600,...,1,1,0,1,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1406,70,11,1998,44850,Petrol,110,1,Blue,0,1600,...,0,1,0,0,1,1,0,0,0,0
1407,69,12,1998,44826,Petrol,110,0,Red,0,1600,...,1,1,0,0,0,1,0,0,0,1
1408,80,1,1998,44444,Petrol,110,1,Blue,0,1600,...,1,1,0,1,1,1,1,0,0,0
1409,75,6,1998,43720,Petrol,110,1,Grey,0,1600,...,0,1,0,0,1,1,0,0,0,1
1410,78,3,1998,43622,Petrol,86,1,Grey,0,1300,...,0,1,0,0,0,0,0,0,0,0
1411,76,5,1998,43532,Petrol,110,0,White,0,1600,...,0,1,0,0,0,1,0,0,0,0
1412,69,12,1998,42800,Petrol,110,1,Black,0,1600,...,0,1,0,0,1,1,0,0,0,0
1413,74,7,1998,42317,Petrol,107,1,Black,1,1600,...,0,1,1,1,0,1,0,1,0,1
1414,80,1,1998,42186,Petrol,110,1,Green,0,1600,...,0,1,0,1,0,1,0,0,0,1
1415,72,9,1998,42000,Petrol,110,1,Red,0,1600,...,0,1,0,0,1,1,0,0,0,0
1416,79,2,1998,40093,Petrol,110,0,Red,0,1600,...,0,1,1,0,0,0,0,1,0,0
1417,79,2,1998,39800,Petrol,107,0,Green,1,1600,...,0,1,0,0,1,1,0,0,0,0
1418,73,8,1998,39168,Petrol,86,0,Red,0,1300,...,0,1,0,0,1,1,0,0,0,0
1419,75,6,1998,38945,Petrol,110,1,Beige,0,1600,...,1,1,0,0,0,1,1,0,0,0
1420,76,5,1998,36537,Petrol,110,0,Red,1,1600,...,0,0,0,0,0,0,0,0,0,0
1421,78,3,1998,36000,Petrol,86,0,Green,1,1300,...,0,1,0,0,0,1,0,0,0,0
1422,78,3,1998,36000,Petrol,110,1,Blue,0,1600,...,1,1,0,0,0,1,1,0,0,0
1423,80,1,1998,35821,Petrol,86,0,Red,1,1300,...,0,1,0,0,0,0,0,0,0,0
1424,73,8,1998,34717,Petrol,86,0,Red,0,1300,...,0,1,0,0,0,0,0,0,0,0
1425,80,1,1998,34000,Petrol,86,1,Silver,0,1300,...,0,0,0,0,0,0,0,0,0,0
1426,78,3,1998,30964,Petrol,110,0,Silver,1,1600,...,0,1,0,0,0,0,0,0,0,1
1427,71,10,1998,29000,Petrol,86,1,Blue,1,1300,...,0,1,0,0,0,1,0,0,0,0
1428,72,9,1998,26000,Petrol,86,0,White,0,1300,...,0,1,0,0,1,1,0,0,0,0
1429,78,3,1998,24000,Petrol,86,1,Green,1,1300,...,0,1,0,0,0,0,0,0,0,1
1430,80,1,1998,23000,Petrol,86,0,Blue,0,1300,...,0,1,0,0,1,1,1,0,0,0
1431,69,12,1998,20544,Petrol,86,1,Blue,0,1300,...,1,1,0,1,1,1,0,0,0,0
1432,72,9,1998,19000,Petrol,86,0,Grey,0,1300,...,0,1,0,0,1,1,0,0,0,0
1433,71,10,1998,17016,Petrol,86,0,Blue,0,1300,...,0,1,0,0,0,1,0,0,0,0
1434,70,11,1998,16916,Petrol,86,1,Grey,0,1300,...,0,0,0,0,0,1,0,0,0,0
1435,76,5,1998,1,Petrol,110,0,Green,0,1600,...,0,1,0,0,0,0,0,0,0,0

In [32]:
set(table['Fuel_Type'])

{u'CNG', u'Diesel', u'Petrol'}